### PR TITLE
Upgrade babel packages to non-beta versions

### LINKED ISSUE #50: Update @babel/packages to non-beta
There some beta packages of @babel that needs to be updated to the latest non-beta version. See packages below:

```
{
    "@babel/core": "^7.0.0-beta.40",
    "@babel/node": "^7.0.0-beta.40",
    "@babel/plugin-proposal-class-properties": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-react": "^7.0.0-beta.40",
    ...
    "babel-loader": "^8.0.0-beta.0",
    ...
    "gulp-babel": "^8.0.0-beta.1",
}
```

Kindly ensure they are compatible and ensure the client side tests pass before raising a PR.

### PR DESCRIPTION
**Pull request by chinchiheather**
Fixes #50 

Updated all packages mentioned in issue as well as gulp-babel
Changed config file to be babel.config.js rather than .babelrc

Project seems to build fine and tests pass

### CODE REVIEW

**Comment by codejockie** [comment]
Did you run the tests?

**Comment by codejockie** [comment]
There are conflicts, please can you resolve the conflicts? You need to pull the latest changes from master branch into your branch.

**Comment by chinchiheather** [comment]
Hi, sorry for the late reply, I have merged master in and resolved the conflicts.
There is an error in the Travis CI build, but I can see that also happened on the latest build for master?

**Comment by codejockie** [comment]
The current master build passes on Travis. Did you push your latest changes yet?

**Comment by chinchiheather** [comment]
Oh right, sorry I followed the wrong link. Yes I pushed my changes, this is my build error
```Seed file failed with error: data and salt arguments required Error: data and salt arguments required``` any ideas?

When I try and run things locally, I am getting the old error ```TypeError: JwtStrategy requires a secret or key``` which I noticed master also had before but has since been resolved

**Comment by codejockie** [comment]
To setup the project locally kindly check the `.env.example` file at the root of the project's directory. That way you'd see what is required to run the tests locally on your machine.
For the test basically, ensure you have a database (Postgres) named `doc_man_test`.

**Comment by chinchiheather** [comment]
Hi,

So after playing around with some things, I think I have worked out why the Travis build is failing. If you look at the build log there is a line:

```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
```
If you follow [that link](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions) it explains that environment variables are only available to PRs coming from within the same repository and that pull requests sent from forked repositories do not have access to encrypted variables or data.

The error I am getting `Error: data and salt arguments required` is coming from the user seeders file where it is trying to call `bcrypt.hashSync` using `process.env.PASSWORD` which my build does not have access to.

What are your thoughts? Have you had any PRs from forked repos before?

**Comment by codejockie** [comment]
> Hi,
> 
> So after playing around with some things, I think I have worked out why the Travis build is failing. If you look at the build log there is a line:
> 
> ```
> Encrypted environment variables have been removed for security reasons.
> See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
> ```
> If you follow [that link](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions) it explains that environment variables are only available to PRs coming from within the same repository and that pull requests sent from forked repositories do not have access to encrypted variables or data.
> 
> The error I am getting `Error: data and salt arguments required` is coming from the user seeders file where it is trying to call `bcrypt.hashSync` using `process.env.PASSWORD` which my build does not have access to.
> 
> What are your thoughts? Have you had any PRs from forked repos before?

That's true. I will pull in your branch and run the tests locally on my machine. If all goes well, I will merge in your PR.

**Pull request merged**
